#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "parser.y".
#

require 'racc/parser.rb'

require 'strscan'

module Namae
  class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 132)

  @defaults = {
    :debug => false,
    :prefer_comma_as_separator => false,
    :include_particle_in_family => false,
    :comma => ',',
    :stops => ',;',
    :separator => %w[and & ;].freeze,
    :et_al => /\s*\b(et\s+al\b\.?|and\s+others\b)\s*\z/i,
    :pronoun => %w[
      he him his she her hers they them their theirs
      xe xem xyr ze zir hir er ihm sie ihr
    ].freeze,
    :title => [
      'Lt Col', 'Lt Gen', 'Maj Gen', 'Brig Gen', *%w[
      Sir Dame Lord Lady Count Countess Baroness Hon.
      General Gen. Admiral Adm Colonel Col. Maj. Captain Capt
      Commander Cmdr Lieutenant Lt Sergeant Sgt Cpl Pvt
      Reverend Rev Pr Father Sister Brother Deaconess Rabbi Vicar
      Archbishop Msgr Professor Prof Doctor Dr
    ]].freeze,
    :trailing_title => %w[
      PhD Ph.D DPhil EdD Ed.D PsyD MD M.D DDS DVM JD J.D RN Esq
    ].freeze,
    :suffix => /\s*\b(JR|Jr|jr|JNR|Jnr|jnr|SR|Sr|sr|SNR|Snr|snr|[IVX]{2,}|[1-9]\d*(st|nd|rd|th))(\.|\b)/,
    :appellation => /\s*\b((mrs?|mx|ms|fr|hr|mme|mlle)\.?|miss|herr|frau)(\s+|$)/i,
    :uppercase_particle => /\s*\b(D[aiu]|De[rs]?|St\.?|Saint|La|Les|V[ao]n)(\s+|$)/
  }

  class << self
    attr_reader :defaults

    # Yields a writable copy of the default options. The new defaults
    # apply to all parsers created afterwards, including each thread's
    # parser instance. List values are frozen: assign a new list instead
    # of changing it in place (e.g., `options[:title] += %w[Sen]`).
    def configure
      options = defaults.dup
      yield options
      @defaults = freeze_options(options)
    end

    # @return [Parser] the current thread's parser, which is replaced
    #   when the defaults change.
    def instance
      parser = Thread.current[:namae]
      parser = Thread.current[:namae] = new unless parser&.defaults.equal?(defaults)
      parser
    end

    def freeze_options(options)
      options.transform_values { |value| value.frozen? ? value : value.dup.freeze }.freeze
    end
  end

  @defaults = freeze_options(@defaults)

  attr_reader :options, :defaults, :input,
    :separator, :title, :trailing_title, :trailing_titles, :single_word, :pronouns

  # @param options [Hash] options that override the current defaults;
  #   the parser's options cannot be changed later.
  def initialize(options = {})
    @defaults = self.class.defaults
    @options = self.class.freeze_options(defaults.merge(options))
    @input = StringScanner.new('')
    compile_patterns
  end

  def debug?
    options[:debug] || ENV['DEBUG']
  end


  def comma
    options[:comma]
  end

  def include_particle_in_family?
    options[:include_particle_in_family]
  end

  def stops
    options[:stops]
  end

  def et_al
    options[:et_al]
  end

  def suffix
    options[:suffix]
  end

  def appellation
    options[:appellation]
  end

  def uppercase_particle
    options[:uppercase_particle]
  end

  def prefer_comma_as_separator?
    options[:prefer_comma_as_separator] && !@single
  end

  def parse(string)
    parse!(string)
  rescue => e
    warn e.message if debug?
    Names.new
  end

  # @param single [Boolean] whether the input is a single name, in which
  #   case commas never separate names.
  def parse!(string, single: false)
    @input = StringScanner.new(normalize(string))
    @single = single
    reset
    names = Names.new(do_parse)
    names.map(&:merge_particles!) if include_particle_in_family?
    names.others = @others
    @pronouns_of.each { |index, pronouns| names[index]&.pronouns = pronouns }
    names
  end

  # Adds an honorific to a name, keeping titles on both sides of the name.
  def honor(name, honorific)
    titles = [honorific.title, name.title].compact
    name.merge(honorific)
    name.title = titles.join(' ') unless titles.empty?
    name
  end

  # Compiles the patterns derived from the options.
  def compile_patterns
    # Separator words (e.g., 'and') match as whole words only, symbols
    # (e.g., '&') need no word boundaries.
    @separator = pattern(:separator) do |words|
      words = words.map do |word|
        word.match?(/\A[[:alnum:]]+\z/) ? "\\b#{Regexp.escape(word)}\\b" : Regexp.escape(word)
      end
      /\s*(#{words.join('|')})\s*/i
    end

    # Titles precede the name; trailing titles follow it, optionally
    # after a comma.
    @title = pattern(:title) do |words|
      /\s*\b(#{titles(words)})(?=\s|\z)\s*/i
    end
    @trailing_title = pattern(:trailing_title) do |words|
      /\s*\b(#{titles(words)})(?![^\s#{stops}])\s*/i
    end

    # Pronouns in parentheses (e.g., '(he/him)'): at least two words, all
    # of them pronouns, separated by slashes or commas.
    @pronouns = pattern(:pronoun) do |words|
      pronoun = /\b(#{words.map { |word| Regexp.escape(word) }.join('|')})\b/i
      /\s*\(\s*(#{pronoun}(\s*[\/,]\s*#{pronoun})+)\s*\)/
    end

    end_of_name = /(#{separator}|\s*#{comma}|\s*\z)/
    @trailing_titles = /(#{trailing_title})+#{end_of_name}/
    @single_word = /[^\s#{stops}]+#{end_of_name}/
  end

  # @return [Regexp] the option itself if it is a pattern; otherwise the
  #   pattern the block builds from the option's list of words.
  def pattern(key)
    value = options[key]
    value.is_a?(Regexp) ? value : yield(value)
  end

  # A trailing period is optional unless the title itself ends with one.
  def titles(words)
    # Longer titles first, so that 'Lt Col' wins over 'Lt'.
    words.sort_by { |word| -word.length }.map { |word|
      word.end_with?('.') ? Regexp.escape(word) : "#{Regexp.escape(word)}\\.?"
    }.join('|')
  end

  def normalize(string)
    string.scrub.strip
  end

  def reset
    @commas, @words, @initials, @suffices, @yydebug = 0, 0, 0, 0, debug?
    @seen_initial = false

    # Titles and appellations are not counted as words; they are only
    # recognized while leading (at the start of a name or the given part
    # of a sort-order name) or, for trailing titles, at the end of a name.
    @leading = true
    @others = false
    @pending = nil
    @name_index = 0
    @pronouns_of = {}
    self
  end

  private

  def stack
    @vstack || @racc_vstack || []
  end

  def last_token
    stack[-1]
  end

  def consume_separator
    return next_token if seen_separator?
    @commas, @words, @initials, @suffices = 0, 0, 0, 0
    @seen_initial = false
    @leading = true
    @name_index += 1
    [:AND, :AND]
  end

  def consume_comma
    @commas += 1
    @leading = true
    [:COMMA, :COMMA]
  end

  def consume_word(type, word)
    @words += 1
    @particle_first = %i[LWORD UPARTICLE].include?(type) if @words == 1
    @leading = false
    @initial = false

    case type
    when :UWORD
      @initials += 1 if word.match?(/^[[:upper:]]+\b/)
      # Only single letters or dotted letters (e.g., 'G', 'J.', 'J.A.')
      # count as initials here, not all-caps words (e.g., 'LEWIS').
      @initial = word.match?(/\A([[:upper:]]\.?|([[:upper:]]\.)+)\z/)
      @seen_initial ||= @initial
    when :SUFFIX
      @suffices += 1
    end

    [type, word]
  end

  def seen_separator?
    !stack.empty? && last_token == :AND
  end

  def suffix?
    !@suffices.zero? || will_see_suffix?
  end

  def will_see_suffix?
    input.rest.strip.split(/\s+/)[0] =~ suffix
  end

  # Trailing titles must follow at least two name words and end the name.
  def will_see_trailing_titles?
    @words >= 2 && input.check(trailing_titles)
  end

  def will_see_initial?
    input.rest.strip.split(/\s+/)[0] =~ /^[[:upper:]]+\b/
  end

  # A comma ends the current name if the name is complete: either it
  # has initials before the last word (e.g., "J. Smith" can only be in
  # display order) or, if commas are preferred as separators, it has
  # at least two words, does not start with a particle (e.g., "Da Silva,
  # Luiz Inácio"), and is not followed by initials or a single word (e.g.,
  # "Brinch Hansen, Per").
  def seen_full_name?
    return false if will_see_suffix?
    return true if @seen_initial && !@initial

    prefer_comma_as_separator? && @words > 1 && !@particle_first &&
      (@initials > 0 || !will_see_initial?) && !will_see_single_word?
  end

  def will_see_single_word?
    input.check(single_word)
  end

  def next_token
    if @pending
      token, @pending = @pending, nil
      return token
    end

    case
    when input.nil?, input.eos?
      nil
    when input.scan(pronouns)
      # Pronouns are not part of the grammar: keep them for the current name.
      @pronouns_of[@name_index] = input[1]
      next_token
    when input.scan(et_al)
      @others = true
      nil
    when input.scan(separator)
      consume_separator
    when input.scan(/\s*#{comma}\s*/)
      if last_token == :COMMA || input.check(separator) || input.check(et_al) ||
          will_see_trailing_titles?
        next_token
      elsif @commas.zero? && !seen_full_name? || @commas == 1 && suffix?
        consume_comma
      else
        consume_separator
      end
    when input.scan(/\s+/)
      next_token
    when @leading && input.scan(title)
      [:TITLE, input.matched.strip]
    when @leading && input.scan(appellation)
      [:APPELLATION, input.matched.strip]
    when will_see_trailing_titles? && input.scan(trailing_title)
      [:TITLE, input.matched.strip]
    when input.scan(suffix)
      suffix = input.matched.strip
      if @commas.zero? && (@words == 1 || @particle_first) && input.check(/\s*#{comma}/)
        # Read 'Gump Jr., Bubba' as 'Gump, Jr., Bubba'.
        token = consume_comma
        @pending = consume_word(:SUFFIX, suffix)
        token
      else
        consume_word(:SUFFIX, suffix)
      end
    when input.scan(uppercase_particle)
      consume_word(:UPARTICLE, input.matched.strip)
    when input.scan(/((\\\w+)?\{[^\}]*\})*[[:upper:]][^\s#{stops}]*/)
      consume_word(:UWORD, input.matched)
    when input.scan(/((\\\w+)?\{[^\}]*\})*[[:lower:]][^\s#{stops}]*/)
      consume_word(:LWORD, input.matched)
    when input.scan(/(\\\w+)?\{[^\}]*\}[^\s#{stops}]*/)
      consume_word(:PWORD, input.matched)
    when input.scan(/('[^'\n]+')|("[^"\n]+")|(\(\s*['"]?[[:upper:]][^()\d.\n]*\))/)
      # Nicknames in quotes or parentheses, e.g., 'Mike', (Mike) or ('Mike');
      # in parentheses, they must not look like '(ed.)' or '(2001)'.
      consume_word(:NICK, input.matched[1...-1].strip.sub(/\A(['"])(.*)\1\z/, '\\2'))
    when input.scan(/[@\d][^\s#{stops}]*[[:alpha:]][^\s#{stops}]*/)
      # Handles and other words starting with @ or a digit
      consume_word(:PWORD, input.matched)
    else
      raise ArgumentError,
        "Failed to parse name #{input.string.inspect}: unmatched data at offset #{input.pos}"
    end
  end

  def on_error(tid, value, stack)
    raise ArgumentError,
      "Failed to parse name: unexpected '#{value}' at #{stack.inspect}"
  end

# -*- racc -*-
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
   -47,    53,   -28,    39,   -50,    40,    23,   -47,   -48,    23,
   -47,   -50,   -49,   -50,   -50,   -48,   -47,   -48,   -48,   -49,
   -31,   -49,   -49,   -47,    19,   -47,   -47,   -31,    73,    28,
    82,    66,    57,    67,    79,    28,    23,    20,   -45,    58,
    17,    14,    18,    11,    21,     7,    19,    42,    15,    17,
    14,    18,    11,    17,    32,    18,    30,    15,    39,    37,
    40,    15,    17,    14,    18,    11,    38,     7,    19,    83,
    15,    39,    37,    40,    39,    37,    40,    45,    39,    38,
    40,    43,    38,    39,    55,    40,   -26,   -26,   -26,    45,
    28,    38,    23,    19,   -26,    17,    57,    18,    45,    66,
    57,    67,    23,    58,     7,    19,    23,    58,    39,    37,
    40,    19,    66,    57,    67,    23,    38,     7,    19,    23,
    58,    66,    57,    67,    19,    66,    57,    67,    23,    58,
     7,    19,    23,    58,    66,    57,    67,    66,    57,    67,
    28,    19,    58,    23,    19,    58,    19,    19,    23,    19,
    45 ]

racc_action_check = [
    14,    34,    14,    11,    15,    11,     3,    14,    17,    34,
    14,    15,    18,    15,    15,    17,    32,    17,    17,    18,
    59,    18,    18,    32,     7,    32,    32,    59,    51,    59,
    63,    63,    63,    63,    63,     8,    51,     1,    63,    63,
     0,     0,     0,     0,     1,     0,     0,    12,     0,     5,
     5,     5,     5,     9,     9,     9,     9,     5,    10,    10,
    10,     9,    21,    21,    21,    21,    10,    21,    21,    64,
    21,    30,    30,    30,    31,    31,    31,    64,    50,    30,
    50,    20,    31,    36,    36,    36,    37,    37,    37,    22,
    27,    36,    29,    46,    37,    41,    41,    41,    47,    42,
    42,    42,    48,    41,    42,    42,    42,    42,    49,    49,
    49,    52,    53,    53,    53,    56,    49,    53,    53,    53,
    53,    62,    62,    62,    61,    73,    73,    73,    62,    62,
    73,    73,    73,    73,    83,    83,    83,    91,    91,    91,
    69,    70,    83,    71,    72,    91,    76,    78,    80,    85,
    90 ]

racc_action_pointer = [
    37,    37,   nil,    -4,   nil,    46,   nil,    15,    26,    50,
    55,     0,    45,   nil,     0,     4,   nil,     8,    12,   nil,
    81,    59,    79,   nil,   nil,   nil,   nil,    81,   nil,    82,
    68,    71,    16,   nil,    -1,   nil,    80,    83,   nil,   nil,
   nil,    92,    96,   nil,   nil,   nil,    84,    88,    92,   105,
    75,    26,   102,   109,   nil,   nil,   105,   nil,   nil,    20,
   nil,   115,   118,    28,    67,   nil,   nil,   nil,   nil,   131,
   132,   133,   135,   122,   nil,   nil,   137,   nil,   138,   nil,
   138,   nil,   nil,   131,   nil,   140,   nil,   nil,   nil,   nil,
   140,   134,   nil ]

racc_action_default = [
    -1,   -59,    -2,    -4,    -6,   -59,    -9,   -11,   -12,   -29,
   -59,   -59,   -59,   -23,   -26,   -27,   -39,   -41,   -42,   -57,
   -59,   -59,    -5,   -53,    -7,    -8,   -10,   -13,   -58,   -51,
   -59,   -59,   -26,   -40,   -51,   -24,   -29,   -28,   -27,   -41,
   -42,   -59,   -30,    93,    -3,   -54,   -55,   -52,   -51,   -59,
   -29,   -51,   -55,   -30,   -25,   -26,   -51,   -47,   -50,   -12,
   -20,   -55,   -59,   -34,   -37,   -43,   -48,   -49,   -14,   -56,
   -55,   -51,   -55,   -30,   -18,   -21,   -55,   -32,   -55,   -35,
   -59,   -44,   -46,   -59,   -15,   -55,   -17,   -22,   -19,   -33,
   -36,   -38,   -16 ]

racc_goto_table = [
     3,    22,    33,     8,     1,    24,    46,    25,    60,    29,
    27,    52,    26,    78,    91,    36,    41,    80,   nil,    75,
   nil,     3,   nil,   nil,     8,    70,    34,   nil,    72,    33,
   nil,     2,   nil,    76,    33,    50,    36,   nil,    68,    87,
    64,    56,   nil,    33,    74,    59,    48,    51,    85,   nil,
   nil,    64,    44,    77,    36,   nil,    59,   nil,    35,     5,
    64,    31,    84,    81,    86,    71,   nil,   nil,    88,   nil,
    89,    64,   nil,   nil,   nil,   nil,    59,    92,    90,    35,
     5,   nil,    49,   nil,    54,   nil,   nil,   nil,   nil,   nil,
   nil,    81,   nil,   nil,   nil,   nil,   nil,    35 ]

racc_goto_check = [
     3,     4,    19,     8,     1,     3,    10,     5,    14,     3,
     8,    10,     7,    16,    17,     9,     9,    18,   nil,    14,
   nil,     3,   nil,   nil,     8,    10,    12,   nil,    10,    19,
   nil,     2,   nil,    10,    19,     9,     9,   nil,    11,    14,
     4,     3,   nil,    19,    11,     8,    12,    12,    10,   nil,
   nil,     4,     2,    11,     9,   nil,     8,   nil,    15,     6,
     4,    13,    11,     3,    11,    12,   nil,   nil,    11,   nil,
    11,     4,   nil,   nil,   nil,   nil,     8,    11,     4,    15,
     6,   nil,    13,   nil,    15,   nil,   nil,   nil,   nil,   nil,
   nil,     3,   nil,   nil,   nil,   nil,   nil,    15 ]

racc_goto_pointer = [
   nil,     4,    31,     0,    -2,     2,    59,     7,     3,     5,
   -23,    -8,    16,    52,   -34,    48,   -49,   -69,   -46,    -7 ]

racc_goto_default = [
   nil,   nil,   nil,    65,    47,     4,    62,     6,    69,     9,
   nil,   nil,    12,    10,   nil,    13,    61,    63,   nil,    16 ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 13, :_reduce_1,
  1, 13, :_reduce_2,
  3, 13, :_reduce_3,
  1, 14, :_reduce_4,
  2, 14, :_reduce_5,
  1, 14, :_reduce_none,
  2, 14, :_reduce_7,
  2, 14, :_reduce_8,
  1, 14, :_reduce_none,
  2, 14, :_reduce_10,
  1, 18, :_reduce_11,
  1, 18, :_reduce_12,
  2, 18, :_reduce_13,
  4, 17, :_reduce_14,
  5, 17, :_reduce_15,
  6, 17, :_reduce_16,
  5, 17, :_reduce_17,
  4, 17, :_reduce_18,
  5, 17, :_reduce_19,
  3, 19, :_reduce_20,
  4, 19, :_reduce_21,
  5, 19, :_reduce_22,
  1, 25, :_reduce_none,
  2, 25, :_reduce_24,
  3, 25, :_reduce_25,
  1, 27, :_reduce_none,
  1, 27, :_reduce_none,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  0, 26, :_reduce_30,
  1, 26, :_reduce_31,
  2, 26, :_reduce_32,
  3, 26, :_reduce_33,
  1, 28, :_reduce_34,
  2, 28, :_reduce_35,
  3, 28, :_reduce_36,
  1, 28, :_reduce_37,
  3, 28, :_reduce_38,
  1, 21, :_reduce_none,
  2, 21, :_reduce_40,
  1, 31, :_reduce_none,
  1, 31, :_reduce_none,
  1, 29, :_reduce_none,
  2, 29, :_reduce_44,
  0, 30, :_reduce_none,
  1, 30, :_reduce_none,
  1, 15, :_reduce_none,
  1, 15, :_reduce_none,
  1, 15, :_reduce_none,
  1, 15, :_reduce_none,
  0, 22, :_reduce_none,
  1, 22, :_reduce_none,
  1, 16, :_reduce_none,
  2, 16, :_reduce_54,
  0, 23, :_reduce_none,
  1, 23, :_reduce_none,
  1, 20, :_reduce_none,
  2, 20, :_reduce_58 ]

racc_reduce_n = 59

racc_shift_n = 93

racc_token_table = {
  false => 0,
  :error => 1,
  :COMMA => 2,
  :UWORD => 3,
  :LWORD => 4,
  :PWORD => 5,
  :NICK => 6,
  :AND => 7,
  :APPELLATION => 8,
  :TITLE => 9,
  :SUFFIX => 10,
  :UPARTICLE => 11 }

racc_nt_base = 12

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "COMMA",
  "UWORD",
  "LWORD",
  "PWORD",
  "NICK",
  "AND",
  "APPELLATION",
  "TITLE",
  "SUFFIX",
  "UPARTICLE",
  "$start",
  "names",
  "name",
  "word",
  "suffices",
  "display_order",
  "honorific",
  "sort_order",
  "titles",
  "u_words",
  "opt_suffices",
  "opt_titles",
  "last",
  "von",
  "first",
  "particle",
  "given",
  "words",
  "opt_comma",
  "u_word" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 11)
  def _reduce_1(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 12)
  def _reduce_2(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 13)
  def _reduce_3(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 15)
  def _reduce_4(val, _values, result)
     result = Name.new(:given => val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 16)
  def _reduce_5(val, _values, result)
     result = Name.new(:given => val[0], :suffix => val[1])
    result
  end
.,.,

# reduce 6 omitted

module_eval(<<'.,.,', 'parser.y', 18)
  def _reduce_7(val, _values, result)
     result = val[0].merge(:family => val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 19)
  def _reduce_8(val, _values, result)
     result = honor(val[1], val[0])
    result
  end
.,.,

# reduce 9 omitted

module_eval(<<'.,.,', 'parser.y', 21)
  def _reduce_10(val, _values, result)
     result = honor(val[1], val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 23)
  def _reduce_11(val, _values, result)
     result = Name.new(:appellation => val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 24)
  def _reduce_12(val, _values, result)
     result = Name.new(:title => val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 25)
  def _reduce_13(val, _values, result)
     result = Name.new(:appellation => val[0], :title => val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 29)
  def _reduce_14(val, _values, result)
             result = Name.new(
           :given => val[0], :family => val[1], :suffix => val[2], :title => val[3]
         )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 35)
  def _reduce_15(val, _values, result)
             result = Name.new(
           :given => val[0], :nick => val[1], :family => val[2], :suffix => val[3], :title => val[4]
         )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 41)
  def _reduce_16(val, _values, result)
             result = Name.new(
           :given => val[0], :nick => val[1], :particle => val[2], :family => val[3], :suffix => val[4], :title => val[5])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 46)
  def _reduce_17(val, _values, result)
             result = Name.new(
           :given => val[0], :particle => val[1], :family => val[2], :suffix => val[3], :title => val[4]
         )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 52)
  def _reduce_18(val, _values, result)
             result = Name.new(
           :particle => val[0], :family => val[1], :suffix => val[2], :title => val[3]
         )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 58)
  def _reduce_19(val, _values, result)
             result = Name.new(
           :nick => val[0], :given => val[1], :family => val[2], :suffix => val[3], :title => val[4]
         )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 65)
  def _reduce_20(val, _values, result)
             result = Name.new(val[2].merge(:family => val[0]), !!val[2][:suffix])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 69)
  def _reduce_21(val, _values, result)
             result = Name.new(val[3].merge(
           :particle => val[0], :family => val[1]
         ), !!val[3][:suffix])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 75)
  def _reduce_22(val, _values, result)
             result = Name.new(val[4].merge(
           :particle => val[0,2].join(' '), :family => val[2]
         ), !!val[4][:suffix])

    result
  end
.,.,

# reduce 23 omitted

module_eval(<<'.,.,', 'parser.y', 82)
  def _reduce_24(val, _values, result)
     result = val.join(' ')
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 83)
  def _reduce_25(val, _values, result)
     result = val.join(' ')
    result
  end
.,.,

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

module_eval(<<'.,.,', 'parser.y', 89)
  def _reduce_30(val, _values, result)
     result = {}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 90)
  def _reduce_31(val, _values, result)
     result = { :title => val[0] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 91)
  def _reduce_32(val, _values, result)
     result = val[0].merge(:title => val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 94)
  def _reduce_33(val, _values, result)
                titles = [val[0].title, val[2]].compact
            result = val[1].merge(val[0].to_h.compact)
            result[:title] = titles.join(' ') unless titles.empty?

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 99)
  def _reduce_34(val, _values, result)
     result = { :given => val[0] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 100)
  def _reduce_35(val, _values, result)
     result = { :given => val[0], :nick => val[1] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 101)
  def _reduce_36(val, _values, result)
     result = { :given => val[0], :suffix => val[2] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 102)
  def _reduce_37(val, _values, result)
     result = { :suffix => val[0] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 103)
  def _reduce_38(val, _values, result)
     result = { :given => val[2], :suffix => val[0] }
    result
  end
.,.,

# reduce 39 omitted

module_eval(<<'.,.,', 'parser.y', 106)
  def _reduce_40(val, _values, result)
     result = val.join(' ')
    result
  end
.,.,

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

module_eval(<<'.,.,', 'parser.y', 111)
  def _reduce_44(val, _values, result)
     result = val.join(' ')
    result
  end
.,.,

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

# reduce 51 omitted

# reduce 52 omitted

# reduce 53 omitted

module_eval(<<'.,.,', 'parser.y', 120)
  def _reduce_54(val, _values, result)
     result = val.join(' ')
    result
  end
.,.,

# reduce 55 omitted

# reduce 56 omitted

# reduce 57 omitted

module_eval(<<'.,.,', 'parser.y', 125)
  def _reduce_58(val, _values, result)
     result = val.join(' ')
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module Namae
