name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    name: ${{ matrix.ruby-version }} ${{ matrix.friendlyName }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        ruby-version:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
        os:
          - ubuntu-latest
        include:
          - os: ubuntu-latest
            friendlyName: Linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Ruby and install bundle
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake
      - name: Upload coverage results
        if: matrix.ruby-version == '3.3'
        continue-on-error: true
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ github.token }}
